### ISSUE TITLE
Test shows up as passing while it isn't

### ISSUE THREAD

**Issue by pdewit** [beyondcode/dusk-dashboard#16]
Hi,

Amazing work on the package!
It seemed to work well, but after a bit of playing around with it I have found that it gives false positives for my tests when running it with the package enabled. I have freshly installed Laravel Dusk and this package on an existing project. The one test I added always ends up as successful even though it's not. The dashboard correctly shows the tests as failing in the steps but not in the console or the counters at the top.

If I run `php artisan dusk` like normal with the package's BaseTestCase import enabled it also gives a false positive.

When I revert the import in DuskTestCase back to the default it ends up as failing again as it should (the random gibberish does not appear in the page).

<img width="612" alt="screenshot 2018-12-13 at 00 28 34" src="https://user-images.githubusercontent.com/488574/49905534-5e7e6700-fe6e-11e8-91db-917a229ad505.png">

```php
public function testExample()
{
    $this->browse(function (Browser $browser) {
        $browser->visit('/login')
                ->assertSee('sdashdkhalskdh');
    });
}
```

Any idea?

**Comment by am-chris** [comment]
I'm running into this issue, too. All of my dusk tests pass but when I use this dusk dashboard it shows about half of them failing. I followed installation instructions.

**Comment by jesephan** [comment]
Based on the screenshot above, this package shows its running additional test `AssertSeeIn` while in reality the test has only one assertion.

**Comment by goper-leo** [comment]
@pdewit did you manage to solve this? I also encounter this. Thanks.

**Comment by pdewit** [comment]
@goper-leo Nope, have not managed to solve this.

**Comment by dklesev** [comment]
it looks like it was forgotten to throw the exception. When adding

```
protected function onNotSuccessfulTest(Throwable $t)
{
    parent::onNotSuccessfulTest($t);
    throw $t;
}
```

to `DuskTestCase.php` it seems to work.

**Comment by bobo52310** [comment]
Still suffer from this issue...
