### ISSUE TITLE
Run single test

### ISSUE THREAD

**Issue by zoispag** [beyondcode/dusk-dashboard#18]
Hi there!

Dashboard looks amazing! 💪 

I've got one question. I have more than 200 tests. When I am writing a new one, it would be great not to have to wait for all of them to see my new test running in the dashboard :)
Is it currently possible to run a single test, or a group, or a filter?

**Comment by nikazooz** [comment]
@zoispag With the latest release any arguments you pass to Dashboard command when you run it will be proxied to Dusk. So if you run Dashboard f.e. with `--filter` option, only filtered tests will be executed. 🙂 
This was the PR: https://github.com/beyondcode/dusk-dashboard/pull/31

**Comment by zoispag** [comment]
@nikazooz that's great news!!! :D :D :D
