### ISSUE TITLE
It does not work for me. Just nothing happens.

### ISSUE THREAD

**Issue by goszowski** [beyondcode/dusk-dashboard#21]
I only have a tabs and simulated browser window. Start tests button not working.
![image](https://user-images.githubusercontent.com/10208931/50054095-151c6900-0147-11e9-9106-a4b304e68700.png)

**Comment by goszowski** [comment]
Yes
![image](https://user-images.githubusercontent.com/10208931/50054123-8c51fd00-0147-11e9-9ebd-7af881cb67bb.png)

**Comment by wuori** [comment]
Same here, the [docs are in the blog post](http://marcelpociot.de/blog/introducing-the-laravel-dusk-dashboard) and once I changed the line it worked fine:

In `DuskTestCase.php` Find and replace this line:

`use Laravel\Dusk\TestCase as BaseTestCase;`

with:

`use BeyondCode\DuskDashboard\Testing\TestCase as BaseTestCase;`

**Comment by goszowski** [comment]
I did it before running the tests. It just does not work.

**Comment by goszowski** [comment]
I can push the repo if You want.
