### ISSUE TITLE
What's the minimum Laravel version that this package supports to? 

### ISSUE THREAD

**Issue by jtrod** [beyondcode/dusk-dashboard#22]
Hi.. Nice package @mpociot , thank you very much. Is this package compatible with any Dusk version? Like way back to Laravel 5.4??  Sorry if it is documented, I think I just missed it.

**Comment by nikazooz** [comment]
Hi @jtrod 
Based on `composer.json` file this package requires latest version of Dusk (v4) running on Laravel 5.6 or 5.7. Hope it's helpful

**Comment by jtrod** [comment]
Thanks for the reply. Yep, it helps.

**Comment by chrispecoraro** [comment]
Does anyone know what it would take to get it working on Laravel 5.5 or does anybody have a fork working? I'll start investigating.
