### ISSUE TITLE
Use config for host. 

### ISSUE THREAD

**Issue by mikepmtl** [beyondcode/dusk-dashboard#23]
dusk-dashboard uses the config value from "app.url" for the host of the dashboard. 
However that value can be something other than the local machine we are testing from when using Virtual Machines.

It would be nice if that value had it's own config key and defaults perhaps to localhost.

**Comment by vesper8** [comment]
I personally use Laravel Dusk to do unconventional things such as grab screenshots on external websites or for example one of my Dusk tests logs in to my bank account, fills out a couple of forms and pays for last month's statement balance

It would be extremely useful to be able to use this tool to test out Dusk scripts while writing them.. so I have the same issue as above, currently this package uses the APP_URL which in my use case is an external website

Could you make it possible to configure which host the dashboard spawn on please @mpociot ?

**Comment by vesper8** [comment]
I created this PR to add this https://github.com/beyondcode/dusk-dashboard/pull/29
