### ISSUE TITLE
'open' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by tyler36** [beyondcode/dusk-dashboard#24]
When I run ```php artisan dusk:dashboard```, I get an error message:
```
Started Dusk Dashboard on port 9773
Your Dusk tests are now being watched.
If the dashboard does not automatically open, visit: http://freshdining.local:9773/dashboard
'open' is not recognized as an internal or external command,
operable program or batch file.
```

I get output in the dashboard, but some screenshots seem look like it has not loaded the CSS yet.

**Comment by tyler36** [comment]
@nikazooz 
Running on Win10. I couldn't see anything on the site that said "Mac only" though.

**Comment by Vasiliy-Bondarenko** [comment]
The same problem in Linux or inside VM with no visual interface.
Please don't use open :)
Or make it mac-specific feature.

**Comment by tyler36** [comment]
Thanks for fixing this in 1.0.3
