### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by erikgaal** [beyondcode/dusk-dashboard#35]
Opening an issue to keep track of the progress on this package regarding support for Laravel 5.8

https://laravel.com/docs/5.8/upgrade

**Comment by Braunson** [comment]
Already supported in commit https://github.com/beyondcode/dusk-dashboard/commit/9ec7c69c049d74f0c0d39273317cf21ef141832a

**Comment by erikgaal** [comment]
Thank you, @geekybeaver
