### ISSUE TITLE
Needs to be updated for Tailwind 1.0

### ISSUE THREAD

**Issue by nie7321** [beyondcode/dusk-dashboard#47]
I installed the dusk dashboard today and noticed it looked quite different from the screenshots.

![Screen Shot 2019-06-12 at 3 57 59 PM](https://user-images.githubusercontent.com/27235866/59385872-e87a9000-8d2a-11e9-9091-58879803e7fe.png)

Using `https://cdn.jsdelivr.net/npm/tailwindcss@0.7.4/dist/tailwind.min.css` instead of the current version of Tailwind makes it look just like the README. 

I believe most of the class names relating to colours were changed in 1.x, so that needs to be updated.

I can take a stab at it?

**Comment by robov** [comment]
I can confirm this

**Comment by cevour** [comment]
Or just import 0.7 for now.

**Comment by ntraykov** [comment]
Same here
