### ISSUE TITLE
Laravel 6.x is not supported

### ISSUE THREAD

**Issue by mrextreme** [beyondcode/dusk-dashboard#60]
> composer require beyondcode/dusk-dashboard --dev
> 
> Using version ^1.1 for beyondcode/dusk-dashboard
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for beyondcode/dusk-dashboard ^1.1 -> satisfiable by beyondcode/dusk-dashboard[1.1.0].
>     - Conclusion: remove laravel/framework v6.10.1
>     - Conclusion: don't install laravel/framework v6.10.1
>     - beyondcode/dusk-dashboard 1.1.0 requires illuminate/console 5.6.*|5.7.*|5.8.* -> satisfiable by laravel/framework[5.8.x-dev], illuminate/console[5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].

**Comment by kerimkuscu** [comment]
Yes. I have a same problem. @mpociot

**Comment by joserick** [comment]
Dusk-Dashboard already supports laravel 6, but they haven't created a new release with the new changes, but you can try directly with the master branch:

`composer require beyondcode/dusk-dashboard:dev-master --dev`

**Comment by kerimkuscu** [comment]
@mrextreme laravel 6 is now supported.
