### ISSUE TITLE
What about Laravel 7.3 support?

### ISSUE THREAD

**Issue by Hukuta** [beyondcode/dusk-dashboard#65]
required ^7.0

can't install on 7.3

**Comment by benhuang1024** [comment]
No official update, I fork a branch, you can try
```
composer require benhuang1024/dusk-dashboard:dev-master --dev
```

**Comment by Hukuta** [comment]
@benhuang1024 , your fork is can be installed, but it seems broken
![Selection_096](https://user-images.githubusercontent.com/3100053/77997766-a150a080-7338-11ea-800c-f318e4d8227d.png)

**Comment by benhuang1024** [comment]
> @benhuang1024 , your fork is can be installed, but it seems broken
> ![Selection_096](https://user-images.githubusercontent.com/3100053/77997766-a150a080-7338-11ea-800c-f318e4d8227d.png)

Sorry, I forgot to update the remote package using use Yosymfony \ ResourceWatcher \ Crc32ContentHash;
Trying now

**Comment by einkinder** [comment]
I would also like to install with Laravel 7.3
