### ISSUE TITLE
guzzle http "^7.0"

### ISSUE THREAD

**Issue by fredattack** [beyondcode/dusk-dashboard#75]
Hello, 

Is there any way to use your package with guzzleHttp "^7.0" ? Some of other package of my app require this version of guzzle and your package require "^6.3" so i have a conflict! 

Can you help me?  

regards

**Comment by jscarl** [comment]
me too, I guess at the packagist repository for dusk-dashboard not updating the guzzlehttp version, my solution is you can install the package over the Github repository

**Comment by dennykuo** [comment]
I use
```composer require --dev beyondcode/dusk-dashboard:dev-master```

It's works.

**Comment by timschwartz** [comment]
> I use
> `composer require --dev beyondcode/dusk-dashboard:dev-master`
> 
> It's works.

I get the following:

Problem 1
    - cboden/ratchet[v0.4.1, ..., v0.4.3] require guzzlehttp/psr7 ^1.0 -> found guzzlehttp/psr7[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - beyondcode/dusk-dashboard dev-master requires cboden/ratchet ^0.4.1 -> satisfiable by cboden/ratchet[v0.4.1, v0.4.2, v0.4.3].
    - Root composer.json requires beyondcode/dusk-dashboard dev-master -> satisfiable by beyondcode/dusk-dashboard[dev-master].

**Comment by timschwartz** [comment]
@mpociot

**Comment by rowlin** [comment]
> > I use
> > `composer require --dev beyondcode/dusk-dashboard:dev-master`
> > It's works.
> 
> I get the following:
> 
> Problem 1 - cboden/ratchet[v0.4.1, ..., v0.4.3] require guzzlehttp/psr7 ^1.0 -> found guzzlehttp/psr7[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command. - beyondcode/dusk-dashboard dev-master requires cboden/ratchet ^0.4.1 -> satisfiable by cboden/ratchet[v0.4.1, v0.4.2, v0.4.3]. - Root composer.json requires beyondcode/dusk-dashboard dev-master -> satisfiable by beyondcode/dusk-dashboard[dev-master].

 composer require --dev beyondcode/dusk-dashboard:dev-master --with-all-dependencies

**Comment by kaiyum2021** [comment]
`composer require --dev beyondcode/dusk-dashboard:* `  would also work.
