### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by adam1010** [beyondcode/dusk-dashboard#80]
Composer won't let me install this on my PHP 8.0 project -- are major code updates needed, or can we just update the composer file to allow for php8 usage?  Thanks!

**Comment by masterwto** [comment]
I'm using PHP8, having same problem.

**Comment by tonycodes** [comment]
same here

**Comment by nabilrawr** [comment]
hey i just wondering when will php 8.0 support will drop? i really interested to use it to test my php 8.0 project

**Comment by StaffCollab** [comment]
Same here

**Comment by icaliman** [comment]
same here

**Comment by mjohnson-ionline** [comment]
same
